### ISSUE TITLE
SIGSEGV nil pointer when using alias for package with version

### ISSUE THREAD

**Issue by alnpokrovsky** [gojuno/minimock#123]
example code
```go
package tests

import "github.com/gofrs/uuid/v5"

type gen = uuid.Gen
```

falls with such runtime exception while I try to call minimock on it:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x104615d8c]

goroutine 1 [running]:
github.com/gojuno/minimock/v3/internal/types.isInterfaceType(...)
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/internal/types/interface.go:174
github.com/gojuno/minimock/v3/internal/types.isInterface(0x0?, {0x0?, 0x9?, 0x10474c6c0?})
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/internal/types/interface.go:63 +0x1c
github.com/gojuno/minimock/v3/internal/types.isExportedInterfaceAlias(0x20?, {0x140007e9b00?, 0x5?, 0x1400097d000?})
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/internal/types/interface.go:110 +0x84
github.com/gojuno/minimock/v3/internal/types.isInterface(0x140007e9b80, {0x140007e9b00, 0x8, 0x8})
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/internal/types/interface.go:65 +0x6c
github.com/gojuno/minimock/v3/internal/types.FindAllInterfaces(0x140007e96c0?, {0x16ba835e0, 0x8})
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/internal/types/interface.go:33 +0x3e8
main.run(0x140002120e0)
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/cmd/minimock/minimock.go:150 +0x168
main.main()
        /Users/apokrovskiyn/go/pkg/mod/github.com/gojuno/minimock/v3@v3.4.1/cmd/minimock/minimock.go:126 +0x118
```

**Comment by alnpokrovsky** [comment]
Opened PR #124 to fix it
